services:
  infisical:
    image: infisical/infisical:v0.161.9

    container_name: infisical

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"

    environment:
      - NODE_ENV=production