services:
  infisical:
    image: infisical/infisical:v0.161.9

    container_name: infisical

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8080:8080"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --quiet http://localhost:8080/api/status || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5